@base_url = http://localhost:5000
@auth_url = http://localhost:8080

### GET_TOKEN 
# @name token 
POST {{auth_url}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailcampaign&client_secret=suv0pl09TPTD0vYk1hyXyOZoZIeJkKaw&username=agenciamartinidigital@gmail.com&password=123456&grant_type=password
> {%
    client.global.set("access_token", response.body.access_token);
%}


### CREATE_CAMPAIGN 
# @name campaign_create
POST {{base_url}}/campaigns/
Authorization: Bearer {{access_token}}
Content-Type: application/json 

{
    "Name": "Hi there!",
    "Content": "Hello World content 2",
    "emails": ["luis@teste.com", "jo@teste.com", "adele@teste.com", "agenciamartinidigital@gmail.com"],
    "createdBy": "luis@teste.com"
}
> {%
    if (response.body && response.body.id) {
        client.global.set("camp_id", response.body.id);
    } else {
        client.log("CREATE_CAMPAIGN falhou. Status: " + response.status + " Body: " + JSON.stringify(response.body));
    }
%}

### PING 
GET {{base_url}}/ping 

### GET
GET {{base_url}}/campaigns/{{camp_id}}
Authorization: Bearer {{access_token}}

### DELETE_CAMPAIGN
DELETE {{base_url}}/campaigns/delete/{{camp_id}}
Authorization: Bearer {{access_token}}

###
PATCH {{base_url}}/campaigns/start/{{camp_id}}
Authorization: Bearer {{access_token}}

