###
GET http://localhost:3000/ping

###
DELETE http://localhost:3000/delete/d976qpdlv9v6kvjcdhk0

### GET_TOKEN
POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailcampaign&client_secret=suv0pl09TPTD0vYk1hyXyOZoZIeJkKaw&username=agenciamartinidigital@gmail.com&password=123456&grant_type=password

> {%
    client.global.set("access_token", response.body.access_token);
%}

###
POST http://localhost:3000/campaigns
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "Name": "change",
    "Content": "change password",
    "emails": ["luis@teste.com", "jo@teste.com"]
}
